version: '3'

services:
  your_service_name:
    image: pexoacr.azurecr.io/hackyeah-ml:latest
    ports:
      - "7001:106"
    volumes:
      - C:\Users\pexoy\Desktop\HackYeah\Model:/model

volumes:
  model_volume: