version: '3'

services:
  your_service_name:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:105"
    volumes:
      - C:\Users\pexoy\Desktop\HackYeah\Model:/model

volumes:
  model_volume: