version: '3'

services:
  hackyeah-ml-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:7000:105"
    networks:  
      - hackyeah-network

volumes:
  model_volume:

networks:
  hackyeah-network:
    external: true