model:
  model_name: orca-mini-13b.ggmlv3.q4_0.bin
  temperature: 0.1
  streaming: false
  max_tokens: 200
  top_k: 40
  top_p: 0.4
data:
  structure_file: llm/data/structure.txt
  context_intro_file: llm/data/context_intro.txt
  llm_query_file: llm/data/llm_query.txt
